Fix errors linking nvddsview.  Undefined reference to nv::Fit::computePrincipalComponent_EigenSolver caused by library ordering (nvmath needs to follow other libraries).  Fixed in multiple other places already, but not this one.